INCLUDE(CMakePushCheckState)
INCLUDE(CheckCCompilerFlag)
INCLUDE(CheckCXXCompilerFlag)

CMAKE_PUSH_CHECK_STATE(RESET)
SET(CMAKE_REQUIRED_FLAGS "-fsanitize=address")
CHECK_C_COMPILER_FLAG("-fsanitize=address" HAVE_CFLAG_SANITIZE_ADDRESS)
CHECK_CXX_COMPILER_FLAG("-fsanitize=address" HAVE_CXXFLAG_SANITIZE_ADDRESS)
CMAKE_POP_CHECK_STATE()

CMAKE_PUSH_CHECK_STATE(RESET)
SET(CMAKE_REQUIRED_FLAGS "-fsanitize=undefined")
CHECK_C_COMPILER_FLAG("-fsanitize=undefined" HAVE_CFLAG_SANITIZE_UNDEFINED)
CHECK_CXX_COMPILER_FLAG("-fsanitize=undefined" HAVE_CFLAG_SANITIZE_UNDEFINED)
CMAKE_POP_CHECK_STATE()

IF (HAVE_CFLAG_SANITIZE_ADDRESS AND HAVE_CXXFLAG_SANITIZE_ADDRESS)
  set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fsanitize=address")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=address")
ENDIF()

IF (HAVE_CFLAG_SANITIZE_UNDEFINED AND HAVE_CFLAG_SANITIZE_UNDEFINED)
  set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fsanitize=undefined")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=undefined")
ENDIF()

